### ISSUE TITLE
Deployments from 3.7 have a different apiVersion in 4.0

### ISSUE THREAD

**Issue by dymurray** [fusor/ocp-velero-plugin#4]
Deployments in Kube 1.7 were under the `apps/v1beta1` apiversion and are now just `apps/v1`. We need to be aware of the cluster version the resource was backed up for and swap the apiVersion when needed.

https://github.com/fusor/ocp-mig-test-data/issues/35

**Comment by sseago** [comment]
Knowing the cluster version for backup and restore will also be needed for the imagestream plugin. @dymurray and I have already discussed this a bit, and the initial idea was a plugin that runs before the other plugins and matches all resource types. For the backup plugin we should set the annotation "openshift.io/backup-ocp-version" to the cluster version (3.11, 3.7, 4.0, etc.), and on the restore plugin we should set "openshift.io/restore-ocp-version"

**Comment by alexander-demicev** [comment]
I've just to create deployments on 3.11 and 4.0, it's working only with ```apps/v1beta1```. I'll try it later on 3.7. Looks like we need to swap apiVersion.

**Comment by dymurray** [comment]
Alright I think that what you guys are seeing is related to the python OCP client and nothing to do with Kubernetes itself. I was able to create this file in OCP 4.0:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

and I was also able to create:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

So this shouldn't be a problem for Velero. It sounds like a bug in the python client that Ansible uses. @alexander-demichev  can you confirm you can create the above files using `oc create`?
